<Loading>: 
    on_enter: root.start_symulation()
    
    BoxLayout:
        orientation:'vertical'
        Label:
            id: symulations_number
            markup: True
            font_size: self.parent.size[0] * 0.05
            text: root.info_text
            halign: 'center'
            valign: 'middle'
    
        Button:
            id: cancle_button
            text: 'Cancle Loading'
            on_press:
                root.cancel_loading()